MarketHub.Customers/Controllers/CatalogController.cs
using MarketHub.Customers.Models;
using MarketHub.Domain.Filters;
using MarketHub.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarketHub.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ILogger<CatalogController> _logger;
        private readonly ICatalogService _catalogService;

        public CatalogController(ILogger<CatalogController> logger, ICatalogService catalogService)
        {
            _logger = logger;
            _catalogService = catalogService;
        }

        public async Task<IActionResult> Index(int id = 1)
        {
            var response = await _catalogService.GetCatalog(id);
            ViewBag.Id = id;
            if(response.StatusCode == Domain.Enums.StatusCode.Ok)
                return View(response.Data!);
            return RedirectToAction("Error");
        }
        [HttpGet]
        public async Task<IActionResult> GetProducts(int id, CatalogFilter filter = null!)
        {
            if(filter == null)
                filter = new CatalogFilter();
            filter.SubcategoryId = id;
            var response = await _catalogService.GetProducts(filter);
            if (response.StatusCode == Domain.Enums.StatusCode.Ok)
                return View(response.Data!);
            return RedirectToAction("Error");
        }
        [HttpPost]
        public async Task<IActionResult> GetProducts(CatalogFilter filter)
        {
            //var response = await _catalogService.GetProducts(filter);
            //if (response.StatusCode == Domain.Enums.StatusCode.Ok)
                return RedirectToAction("GetProducts", filter);
            //return RedirectToAction("Error");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarketHub.Customers/Controllers/OrderController.cs
using MarketHub.Customers.Service.Implementations;
using MarketHub.Customers.Service.Interfaces;
using MarketHub.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MarketHub.Customers.Controllers
{
	[Authorize]
	public class OrderController : Controller
	{
		private readonly IOrderService _orderService;
		public OrderController(IOrderService orderService)
		{
			_orderService = orderService;
		}
		private int GetUserId() => Convert.ToInt32(User.FindFirst("userId")!.Value);
		[HttpGet]
		public async Task<IActionResult> GetPreorder(int[] productsId)
		{
			var response = await _orderService.GetBasket(productsId);
			if (response.StatusCode == Domain.Enums.StatusCode.Ok)
				return View(response.Data);
			return RedirectToAction("Error");
		}
		[HttpPost]
		public async Task<IActionResult> MakeOrder(OrderViewModel model)
		{
			var response = await _orderService.MakeOrder(GetUserId(),
				model.Adress, model.Phone, model.Sum,
				model.ProductsId, model.SizesId, model.AmountsId, model.basketProductsId);
			if(response.StatusCode == Domain.Enums.StatusCode.Ok)
				return RedirectToAction("OrderMade");
			return RedirectToAction("Error");
		}
		[HttpGet]
		public IActionResult OrderMade()
		{
			return View();
		}
		[HttpGet]
		public async Task<IActionResult> GetMyOrders()
		{
			var response = await _orderService.GetCustomerOrders(GetUserId());
			if (response.StatusCode == Domain.Enums.StatusCode.Ok)
				return View(response.Data);
			return RedirectToAction("Error");
		}
	}
}

MarketHub.Customers/Controllers/ProductController.cs
using MarketHub.Customers.Service.Interfaces;
using MarketHub.Domain.Abstractions.Responses;
using MarketHub.Domain.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MarketHub.Customers.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        private int GetUserId() => Convert.ToInt32(User.FindFirst("userId")!.Value);
        [HttpGet]
        public async Task<IActionResult> GetProduct(int id)
        {
            var response = await _productService.GetProduct(id);
            if(response.StatusCode == Domain.Enums.StatusCode.Ok)
            {
                return View(response!.Data);
            }
            return RedirectToAction("Error");
        }
        [HttpGet]
        public async Task<IActionResult> GetProductBySize(int id, int sizeId)
        {
            IBaseResponse<ProductViewModel> response;
            if (User.Identity!.IsAuthenticated) 
                response = await _productService.GetProductBySize(id, sizeId, GetUserId());
            else
                response = await _productService.GetProductBySize(id, sizeId, null);

            if (response.StatusCode == Domain.Enums.StatusCode.Ok)
            {
                return View("GetProduct", response!.Data);
            }
            return RedirectToAction("Error");
        }
    }
}

MarketHub.Customers/Views/Order/GetMyOrders.cshtml
@model List<OrderEntity>
@{
	ViewData["Title"] = "Мои заказы";
}
<h1>Мои прошлые заказы</h1>
@if (Model.Count == 0)
{
	<h2>Не найдено ни одного заказа</h2>
}
<div>
@foreach(var order in Model.OrderByDescending(x => x.Id))
{
	<div>
		<h3>Заказ №@order.Id <span class="badge bg-primary">@order.OrderStatus!.Name</span></h3>
		<p>Дата заказа: @order.OrderDate</p>
		<p>Сумма: @order.Sum ₽</p>
		<div>
			<div class="accordion" id="accordion-@order.Id">
					<div class="accordion-item">
						<h2 class="accordion-header" id="heading-@order.Id">
							<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@order.Id" aria-expanded="false" aria-controls="collapse-@order.Id">
								Подробнее
							</button>
						</h2>
						<div id="collapse-@order.Id" class="accordion-collapse collapse" aria-labelledby="heading-@order.Id" data-bs-parent="#accordion-@order.Id">
							<div class="accordion-body">
								<h3>Товары</h3>
								<div class="d-flex flex-wrap">
									@foreach (var product in order.OrdersProducts)
									{
										<div class="card mb-3" style="width:450px; margin-right:25px;">
											<div class="row g-0">
												<div class="col">
													@if (@product.Img == "")
													{
														<img src="~/img/Default/default.jpg" class="product-card__img" style="width:200px; height:240px; object-fit:cover;" alt="@product.ProductName">
													}
													else
													{
														<img src="@product.Img" class="card-img-top" style="width:200px; height:240px; object-fit:cover;" alt="@product.ProductName">
													}
												</div>
												<div class="col">
													<div class="card-body">
														<h5 class="card-title">@product.ProductName</h5>
														<p class="card-text">Продавец: @product.SellerName</p>
														<p class="card-text">Количество: @product.Amount</p>
														<p class="card-text">Цвет: @product.Color</p>
														<a asp-action="GetProductBySize" asp-controller="Product" asp-route-id="@product.ProductId" asp-route-sizeId="@product.SizeId" style="background: #122d5c;color: #fff;border-radius: 50px;font-size: 14px;padding: 10px 40px;" class="btn">К товару</a>
													</div>
												</div>
											</div>
										</div>
									}
								</div>
							</div>
						</div>
					</div>
			</div>
		</div>
	</div>
	<hr />
}
</div>

MarketHub.Customers/Views/Order/GetPreorder.cshtml
@model OrderViewModel

@{
	ViewData["Title"] = "Оформление заказа";
	int sum = 0;
}
@section Styles {
	<link rel="stylesheet" href="~/css/Order/orders.css" asp-append-version="true" />
}
<div class="container">
	<h1 class="text-center mt-3 mb-2">Оформление заказа</h1>
	<form asp-controller="Order" asp-action="MakeOrder" class="preorder" method="post">
		<div class="preorder__input-container">
			<label asp-for="@Model.Adress">Адресс</label>
			<input asp-for="@Model.Adress" type="text" class="preorder__input" required />
			<label asp-for="@Model.Phone">Номер телефона</label>
			<input asp-for="@Model.Phone" type="tel" min="11" max="11" class="preorder__input" required />
		</div>
		<h2>Ваш заказ</h2>
		<div class="preorder__product-container">
			@foreach(var product in Model.Basket!.BasketProducts)
			{
				<div class="preorder__product-info">
					<div>
						<h3 class="product__name">(@product.Size!.Name) @product.Product!.Name</h3>
						@if (product.Product!.Img == "")
						{
							<img src="~/img/Default/default.jpg" class="product-card__img product__img" alt="@product.Product!.Name">
						}
						else
						{
							<img src="@product.Product!.Img" class="card-img-top product__img" alt="@product.Product!.Name">
						}
					</div>
					<p style="font-size:50px;">@product.Product.Price ₽</p>
					<p class="product__amount">@product.ProductsCount</p>
				</div>
				<hr />
				{
					sum = sum + (product.ProductsCount * (int)product.Product.Price);
				}
				<div>
					<input name="productsId" type="checkbox" value="@product.ProductId" checked hidden/>
					<input name="sizesId" type="checkbox" value="@product.SizeId" checked hidden/>
					<input name="amountsId" type="checkbox" value="@product.ProductsCount" checked hidden/>
					<input name="basketProductsId" type="checkbox" value="@product.Id" checked hidden />
				</div>
			}
		</div>
		<input asp-for="@Model.Sum" type="number" value="@sum"  hidden />
		<input type="submit" class="preorder__btn" value="Оформить" />
	</form>
</div>

MarketHub.Customers/Views/Order/OrderMade.cshtml
@{
    ViewData["Title"] = "Заказ оформлен";
}
@section Styles {

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Catalog/style.css" asp-append-version="true" />
}
<div class="container banner catalog__banner">
    <div class="banner__body">
        <div class="banner__run-line">MarketHubMarketHub</div>
        <div class="banner__square square">
            <div class="square__line"></div>
            <div class="square__text">Найди свой стиль</div>
            <div class="square__line"></div>
        </div>
        <img src="~/img/Order/male.png" alt="maleImg" class="banner__male">
        <img src="~/img/Order/female.png" alt="femaleImg" class="banner__female">
        <div class="banner__card">
            <div class="banner__title" style="font-size:64px;">Заказ оформлен</div>
            <div class="banner__text">Спасибо за заказ</div>
            <a asp-action="Index" asp-controller="Catalog" class="banner__btn">Перейти в каталог</a>
        </div>
        <div class="banner__run-line">MarketHubMarketHub</div>
    </div>
</div>