MarketHub.Customers/Controllers/BasketController.cs
using MarketHub.Customers.Service.Interfaces;
using MarketHub.Domain.jsonRequest;
using MarketHub.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MarketHub.Customers.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;
        public BasketController(IBasketService basketService)
        {
            _basketService = basketService;
        }
        private int GetUserId() => Convert.ToInt32(User.FindFirst("userId")!.Value);
        [HttpGet]
        public async Task<IActionResult> GetBasket()
        {
            var response = await _basketService.GetBasket(GetUserId());
            if (response.StatusCode == Domain.Enums.StatusCode.Ok)
                return View(response.Data);
            return RedirectToAction("Error");
        }
        [HttpPost]
        //public async Task<IActionResult> AddProductToBasket(int productId, int sizeId, int productsCount)
        public async Task<bool> AddProductToBasket([FromBody] BasketInput basketInput)
        {
            var response = await _basketService.AddProductToBasket(GetUserId(), basketInput.productId, basketInput.sizeId, basketInput.productsCount);
            if(response.StatusCode == Domain.Enums.StatusCode.Ok)
                return response.Data;
            return response.Data;
        }
		[HttpPost]
        public async Task<IActionResult> FirstAddProductToBasket(int productId, int sizeId, int productsCount)
        {
			var response = await _basketService.AddProductToBasket(GetUserId(), productId, sizeId, productsCount);
			if (response.StatusCode == Domain.Enums.StatusCode.Ok)
				return RedirectToRoute(new { controller = "Product", action = "GetProductBySize", id = productId, sizeId = sizeId });
			return RedirectToAction("Error");
		}
		[HttpPost]
        public async Task<bool> RemoveProductFromBasket([FromBody] BasketInput basketInput)
        {
            var response = await _basketService.RemoveProductFromBasket(GetUserId(), basketInput.productId, basketInput.sizeId);
            if (response.StatusCode == Domain.Enums.StatusCode.Ok)
				return response.Data;
			return response.Data;
		}
        [HttpPost]
        public IActionResult MakeOreder(int[] productsId)
        {
            if(productsId.Length > 0)
				return RedirectToRoute(new { controller = "Order", action = "GetPreorder", productsId = productsId });
			return RedirectToAction("Error");
		}
    }
}

MarketHub.Customers/Controllers/CatalogController.cs
using MarketHub.Customers.Models;
using MarketHub.Domain.Filters;
using MarketHub.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarketHub.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ILogger<CatalogController> _logger;
        private readonly ICatalogService _catalogService;

        public CatalogController(ILogger<CatalogController> logger, ICatalogService catalogService)
        {
            _logger = logger;
            _catalogService = catalogService;
        }

        public async Task<IActionResult> Index(int id = 1)
        {
            var response = await _catalogService.GetCatalog(id);
            ViewBag.Id = id;
            if(response.StatusCode == Domain.Enums.StatusCode.Ok)
                return View(response.Data!);
            return RedirectToAction("Error");
        }
        [HttpGet]
        public async Task<IActionResult> GetProducts(int id, CatalogFilter filter = null!)
        {
            if(filter == null)
                filter = new CatalogFilter();
            filter.SubcategoryId = id;
            var response = await _catalogService.GetProducts(filter);
            if (response.StatusCode == Domain.Enums.StatusCode.Ok)
                return View(response.Data!);
            return RedirectToAction("Error");
        }
        [HttpPost]
        public async Task<IActionResult> GetProducts(CatalogFilter filter)
        {
            //var response = await _catalogService.GetProducts(filter);
            //if (response.StatusCode == Domain.Enums.StatusCode.Ok)
                return RedirectToAction("GetProducts", filter);
            //return RedirectToAction("Error");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarketHub.Customers/Controllers/ProductController.cs
using MarketHub.Customers.Service.Interfaces;
using MarketHub.Domain.Abstractions.Responses;
using MarketHub.Domain.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MarketHub.Customers.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        private int GetUserId() => Convert.ToInt32(User.FindFirst("userId")!.Value);
        [HttpGet]
        public async Task<IActionResult> GetProduct(int id)
        {
            var response = await _productService.GetProduct(id);
            if(response.StatusCode == Domain.Enums.StatusCode.Ok)
            {
                return View(response!.Data);
            }
            return RedirectToAction("Error");
        }
        [HttpGet]
        public async Task<IActionResult> GetProductBySize(int id, int sizeId)
        {
            IBaseResponse<ProductViewModel> response;
            if (User.Identity!.IsAuthenticated) 
                response = await _productService.GetProductBySize(id, sizeId, GetUserId());
            else
                response = await _productService.GetProductBySize(id, sizeId, null);

            if (response.StatusCode == Domain.Enums.StatusCode.Ok)
            {
                return View("GetProduct", response!.Data);
            }
            return RedirectToAction("Error");
        }
    }
}

MarketHub.Customers/Views/Product/GetProduct.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = Model.Name + " - MarketHub";
    float mark = 0;
    if(Model.Reviews.Count  != 0)
        mark = Model.Reviews.Select(x => x.Stars).Average();
}
@section Styles {
    <link rel="stylesheet" href="~/css/Products/GetProduct.css" asp-append-version="true" />
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-action="Index" asp-controller="Home">Главная</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-action="Index" asp-controller="Catalog" asp-route-id="@Model.Subcategory.CategoryId">@Model.Subcategory!.Category!.Name</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-action="GetProducts" asp-controller="Catalog" asp-route-id="@Model.SubcategoryId">@Model.Subcategory!.Name</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            @Model.Name
        </li>
    </ol>
</nav>
<div class="product">
    <div class="product__table">
        <div class="product__img">
            @if (Model.Img == "")
            {
                <img src="/img/Default/default.jpg" class="product-card__img" alt="@Model.Name">
            }
            else
            {
                <img src="@Model.Img" alt="@Model.Name" class="product__img">
            }
        </div>
        <div class="product__info info">
            <h3 class="product__name"> @Model.Name</h3>
            <div class="review-info">
                <div class="review-info__stars-block main-mark">
                    <div class="star"></div>
                    <div class="star"></div>
                    <div class="star"></div>
                    <div class="star"></div>
                    <div class="star"></div>
                    <span class="star-value" id="main-mark">@mark.ToString("0.0")</span>
                </div>
                <div class="review-info__amount">
                    <a href="#customer-reviews">Отзывов: @Model.Reviews.Count</a>
                </div>
            </div>
            <p class="product__color">Цвет: <b id="color">@Model.Color</b></p>
            <p class="product__size">Размер: <b id="size"></b></p>
            <div class="product__size-container">
                @foreach(var size in Model.Sizes)
                {
                    if(Model.CurrentSize!.Id == size.Id)
                    {

                        <a asp-controller="Product" asp-action="GetProductBySize" asp-route-id="@Model.Id" asp-route-sizeId="@size.Id">
                            <div class="product__size-icon product__size-icon_active" title="@size.Amount" data-size-amount="@size.Amount">@size.Name</div>
                        </a>
                    }
                    else
                    {
                        if(size.Amount > 0)
                        {
                            <a asp-controller="Product" asp-action="GetProductBySize" asp-route-id="@Model.Id" asp-route-sizeId="@size.Id">
                                <div class="product__size-icon" title="@size.Amount" data-size-amount="@size.Amount">@size.Name</div>
                            </a>
                        }
                        else
                        {
                            <div class="product__size-icon" title="@size.Amount" data-size-amount="@size.Amount">@size.Name</div>
                        }
                    }
                }
            </div>
        </div>
        <div class="product__panel">
            <div class="product__operation">
                <h2 class="product__price">@Model.Price₽</h2>
                @if (User.Identity!.IsAuthenticated)
                {

                        @if (@Model.CurrentBasket != null)
                        {
                            <div>
                                <button id="minus-btn" class="plus" class="basket-btn">-</button>
                                <input id="product-count" class="input-field" name="productsCount" type="number" min="0" max="@Model.CurrentSize!.Amount" data-productId="@Model.CurrentBasket.ProductId" data-sizeId="@Model.CurrentSize.Id" value="@Model.CurrentBasket.ProductsCount" onkeypress="return false;" required />
                                <button id="plus-btn" class="minus" class="basket-btn">+</button>
                            </div>
                        }
                        else
                        {
                            <form asp-controller="Basket" asp-action="FirstAddProductToBasket" method="post" asp-route-productId="@Model.Id" asp-route-sizeId="@Model.CurrentSize.Id">
                                <input name="productsCount" type="number" min="1" max="@Model.CurrentSize!.Amount" value="1" hidden required />
                                <button type="submit" class="basket-btn">Добавить в корзину</button>
                            </form>
                        }
                }
                else
                {
                    <a asp-controller="Account" asp-action="Login" class="basket-btn" style="text-align: center;">Добавить в корзину</a>
                }
                <div class="product__amount"><img src="~/img/Product/sfdsf.png" alt=""> В наличии <span id="amount">@Model.CurrentSize!.Amount</span></div>
            </div>
            <div class="product__seller">
                <img src="~/img/Product/uikkyuj.png" alt="@Model.Seller!.Name">
                @Model.Seller.Name
            </div>
        </div>
        <div class="product__description description">
            <h4 class="description__title">О товаре</h4>
            <p class="description__text">@Model.Description</p>
        </div>
        <div class="product__reviews reviews">
            <h4 class="reviews__title">Отзывы</h4>
            <div class="reviews__column">
                @if (!User.Identity!.IsAuthenticated)
                {
                    <div class="alert alert-primary" role="alert">
                        Чтобы оставить комментарий, необходимо <a asp-controller="Account" asp-action="Login" style="color:inherit; text-decoration: underline;">войти</a> в аккаунт.
                    </div>
                }
                else
                {
                    <div class="review">
                        <div class="review__header">
                            <h5 class="review__title">Напишите свой отзыв!</h5>
                            <div class="review-info__stars-block star-label-block">
                                <div class="star star-label" data-pos="5"></div>
                                <div class="star star-label" data-pos="4"></div>
                                <div class="star star-label" data-pos="3"></div>
                                <div class="star star-label" data-pos="2"></div>
                                <div class="star star-label" data-pos="1"></div>
                            </div>
                        </div>
                        <textarea class="review__input" id="review__value" placeholder="Напишите отзыв" maxlength="1000"></textarea>
                        <button class="review__send" id="review__send-btn" data-productId = "@Model.Id" data-customerId="@User.FindFirst("userId").Value" disabled>Отправить</button>
                    </div>
                }
                <div id="customer-reviews">
                @foreach(var review in Model.Reviews.Take(5).ToList())
                {
                    <div class="review" id="r-@review.Id">
                        <div class="review__header">
                            <h5 class="review__customer-name">@review.Customer!.Name</h5>
                            <div class="review-info__stars-block">
                            @for (int i = 0, j = 1; i < 5; i++)
                            {
                                if(j++ <= (int)review.Stars)
                                    { <div class="star star_active"></div> }
                                else{<div class="star"></div>}
                            }
                            </div>
                        </div>
                        <p class="review__date">@review.Date.ToString("D")</p>
                        <p class="review__text">@review.Text</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                @if(User.FindFirst("userId").Value == review.Customer.Id.ToString())
                                {
                                    <button id="review__delete-btn" data-reviewId="r-@review.Id" data-productId="@Model.Id" data-customerId="@User.FindFirst("userId").Value" class="btn btn-danger">Удалить</button>
                                }
                            }
                    </div>
                }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/js/Product/size.js"></script>
    <script src="~/js/Product/review.js"></script>
    <script src="~/js/Product/basket.js"></script>
}